-- 0003 兼容旧版（Node 版）已有的库：补齐新列，旧的明文列改为可空（数据由启动引导迁移并加密后清空）
ALTER TABLE api_configs ADD COLUMN IF NOT EXISTS base_url VARCHAR(500) NOT NULL DEFAULT '';
ALTER TABLE api_configs ADD COLUMN IF NOT EXISTS api_key_enc TEXT NULL;
ALTER TABLE api_configs MODIFY COLUMN IF EXISTS config_json TEXT NULL;

ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS module VARCHAR(50) NOT NULL DEFAULT '';
ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS target VARCHAR(255) NOT NULL DEFAULT '';
ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS link VARCHAR(500) NOT NULL DEFAULT '';
ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS success TINYINT NOT NULL DEFAULT 1;
ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS duration_ms INT NOT NULL DEFAULT 0;
